service: serverless-chrome-examples

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1
  environment:
    SLS_DEBUG: "*"
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true

plugins:
  - serverless-plugin-chrome
  - serverless-webpack

custom:
  chrome:
    flags:
      - --window-size=1280x1696 # Letter size
      - --hide-scrollbars
  # webpack: ./webpack.config.js
  webpackIncludeModules: true

functions:
  puppeteer:
    description: Headless Chrome using puppeteer
    memorySize: 1024
    timeout: 30
    handler: src/handlers/puppeteer.default
    events:
      - http:
          path: puppeteer
          method: get

  version-info:
    description: Headless Chrome Serverless-framework version info example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/version.default
    events:
      - http:
          path: version-info
          method: get

  request-logger:
    description: Headless Chrome Serverless-framework request logging example
    memorySize: 1024
    timeout: 30
    handler: src/handlers/requestLogger.default
    events:
      - http:
          path: request-logger
          method: get

resources:
  Resources:
    ApiGatewayRestApi:
      Properties:
        BinaryMediaTypes:
          - "*/*"

    # Enable X-Ray tracing on Lambda functions
    # ScreenshotLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
    # PdfLambdaFunction:
    #   Properties:
    #     TracingConfig:
    #       Mode: Active
